gengo/goship

- goship.go
Message will look something like this:
goship: admin successfully deployed to **staging**.
> Make env name in bold text in deploy notification messages

- templates/index.html
This PR is a simple update to add the **project name** to the confirmation dialog for better clarity:
> [#92191452] add project name to confirm dialog message

- templates/index.html
This PR updates the plugin columns in the home page leftwards by 1 column space so that the `deployed revisions` column is next to the deploy button.
screenshot below:
> shift plugin columns left so deployed versions show up besides deploy button

- plugins/travis/travis.go
- plugins/travis/travis_test.go
This PR updates the Travis plugin by defining a minimum width for the the Travis plugin column. This ensures that the `Build Status` wording.
current issue:
when project has no travis build, the `Build Status` header *breaks* on default.
> [update] add min width for travis plugin

- .travis.yml
- goship.go
- goship_test.go
- helpers/staticfiles_test.go
- lib/goship.go
- plugins/helloworld/helloworld.go
- plugins/pivotal/pivotal.go
- plugins/pivotal/pivotal_test.go
- plugins/travis/travis.go
- plugins/travis/travis_test.go
- static/js/pivotal.js
- templates/index.html
original story:
This PR updates Goship such that the Pivotal story plugin's logic is rendered on the frontend (javascript) instead (so that Pivotal stories are loaded only on demand; see screenshots below)
The main javascript code has been a port of an existing Chrome extension by @slamice, and this PR adapts it such that:
- we do not load all Pivotal stories and their statuses all at once; instead, Goship user presses the `Get Stories` button and the Pivotal stories are loaded
- alerts are shown if no associated stories found in Github commit messages, or if the Goship server may still be loading diffs.
-----
> [#92205364] pivotal plugin frontend

- static/js/pivotal.js
This PR updates the Pivotal javascript such that:
- while project diffs are still loading, a press of the `Get Stories` button fetches project diffs (and thereby Github commits) again on demand (so that fetches of Pivotal stories are up to date)
- `Get Stories` button to stay even after loading pivotal stories encounter any error.
> [#92205364] (pivotal plugin) fetch pivotal diffs on demand

- static/js/pivotal.js
> pivotal plugin
This PR ensures that when a Github commit message contains multiple ticket IDs (e.g., `[#1234] [#5678] add tests`, **all** ticket IDs are captured
> [#92205364] (pivotal) ensure multiple pivotal ticket IDs captured

- static/js/pivotal.js
This PR updates the pivotal plugin such that UI improvements are made.
- instead of Javascript's `alert` functions, we update the table cells right away to inform user if no Pivotal stories are found
- upon  refreshing individual project's statuses, the `Get stories` button reappears for user to recheck the Pivotal stories if need be again.
screenshots
> [#92205364] small UI improvements for Pivotal plugin

- README.md
This PR fixes some typo in the example setup of ETCD in the README docs.
This is important as the ETCD parser expects the keys in [be in a certain hierarchy](https://github.com/gengo/goship/blob/master/lib/goship.go#L263) (following the current example would result in a error thrown by Goship).
> [update] fix typos in etcdctl section of README

- static/js/pivotal.js
This PR updates the Pivotal plugin (javascript) such that a `Loading...` text is shown while the script fetches the pivotal stories.
> [#92205364] [pivotal] add Loading text when fetching pivotal stories

- templates/index.html
This PR ensures that the `(diff)` link opens the Github commit diff page in a new tab instead of current tab.
> open github diff page in new tab

- .gitignore
- goship.go
- goship_test.go
- lib/goship.go
- templates/index.html
This PR removes the check to show the deploy button only if there is a diff between deployed code and the git repo. 
This check didn't consider other possible conditions needing a re-deploy, even when there is no change in deployed app code base.
Changes in chef code base, base instances change etc, are a few such cases.
> Always show deploy option

- tools/deploy/deploy.go
In certain situations there is a need to run a custom run list. For example, if you need to put an nginx proxy in maintenance mode,  you can use a custom recipe with this option to achieve that.
> Allow custom chef run list

- lib/config/types.go
- lib/pivotal/client.go
TODO: Gengo specific requests are getting too tightly coupled with the main Goship. We should be careful to separate Gengo specific features as plugins because other users may not have the same use case as us.
Having an idea of pre-deploy and post-deploy hooks that are accessible via plugin might be worth considering.
> [#102836166] Add Pivotal tag on release to live

- lib/config/types.go
Avoid concurrent API call because it causes dead-lock in their server-side.
> [#108834896] Workaround for a dead-lock bug in Pivotal Tracker

- tools/deploy/deploy.go
We need to find a way to keep remote chef version sync every time we proceed a deploy. I suggest we should use bootstrap as default deploy command. It takes more time to deploy but is much safer.
> [#109937778] change defautl value of bootstrap flag to true

- static/js/pivotal.js
It was very hard to identify before deploying if there are any other repository dependencies. In this PR I check pivotal story activity to check if there are any GitHub activity like commits and grab repository names from there. So, if the developer doesn't properly add pivotal story ID to his commits then this functionality won't work.
Also some code refactoring.
> Show story dependencies count and a list of GitHub repositories

- static/js/pivotal.js
This is just an attempt to add some handling on when the ajax requests fail.
> [update] add on error handlers for jquery ajax events

- static/js/pivotal.js
related PR: https://github.com/gengo/goship/pull/186
This PR fixes the issue when console.error is passed as a function to call in `ajaxError()`.
We need to bind console function to console itself.
> [fix] bind console.error function to console itself

- static/js/pivotal.js
story: https://www.pivotaltracker.com/story/show/114274829
This PR updates the Pivotal javascript such that we can gracefully handle the situation when Pivotal API returns an error (e.g., story not found for pivotal ticket ID)
The earlier PR(https://github.com/gengo/goship/pull/187) ensures that the unsuccessful request on Pivotal API would be logged as well.
Else, what is currently happening now, is that the UI continues to show `Loading...` and does not display any story statuses for the successful / found pivotal stories.
> [#114274829] handle when pivotal story not found

- handlers/deploy-page/handler.go
- templates/deploy.html
- templates/index.html
Verify timestamp before deploying. This will help to prevent unexpected deployment when we try to open a closed tab.
> [#121188957] prvent deployment retrigger
