gengo/goship

goship.go
goship_test.go
templates/base.html
templates/deploy.html
templates/index.html

This PR just tries to help clean up some of the codes written in the test file.
- use single quotes whenever possible in Javascript (following [conventions from AirBnB team](https://github.com/airbnb/javascript#strings))
- add missing semi-colons
- fix some typos

fix some typos, clean up some codes

---

templates/index.html

This PR cleans up some javascript syntax.
@ramen74 for your perusal :bow:

[#92205218] clean up some js syntax

---

templates/base.html

* aligned table contents on middle
* applied radius for avatar icon
* fixed logo position

Small css changes

---

static/css/styles.css

* Fixed css style to apply vertical align for table td elements
* Applied base height for table td elements, to avoid changing height rattled

Fixed style issue

---

plugins/travis/travis.go
plugins/travis/travis_test.go

Cleaner look when the pivotal link is broken.

Fix for link when there is no project in travis.

---

goship.go
lib/goship.go
plugins/helloworld/helloworld.go
plugins/pivotal/pivotal.go
plugins/pivotal/pivotal_test.go
plugins/travis/travis.go
plugins/travis/travis_test.go
templates/index.html

story: https://www.pivotaltracker.com/n/projects/969040/stories/92205364
This PR updates Goship with a Pivotal plugin that, based on the `[#ticket_id]` matches in github commit messages, shows the progress / status of each of these tickets.
As such, some refactoring of `PostPivotalComments` from main into the library was done to reuse these codes. Also, added an `goship.Environment` variable for plugin's `RenderDetail` method.

[#92205364] pivotal ticket status plugin

---

tools/deploy/deploy.go

Currently, this script only works under the condition to use `master` of deployment tool repository. But sometimes I want to use a different branch temporally while testing the deployment script. I think this functionality is necessary especially when you have multiple environment hosting goship server, e.g. staging and live.

allow branch setting on deployment tool repository

---

README.md
tools/deploy/deploy.go

- Fix deployment script problem.
- Add explanation for etcd related config.

small fixes

---

handlers/commits/handler.go
handlers/commits/payload.go
home_handler.go
lib/config/load.go
lib/config/types.go
lib/config/types_test.go
lib/revision/control.go
lib/revision/github/control.go
lib/revision/github/control_test.go
plugins/helloworld/helloworld.go
plugins/pivotal/pivotal.go
plugins/pivotal/pivotal_test.go
plugins/plugin/plugin.go
plugins/travis/travis.go
plugins/travis/travis_test.go
templates/index.html

This is a preparation for adding docker support.
The decoupling helps us to add another revision control mechanism.

Decouple view parameters from config parameters

---

Godeps/Godeps.json
handlers/commits/handler.go
lib/config/load.go
lib/config/load_test.go
lib/config/lock.go
lib/config/lock_test.go
lib/config/store.go
lib/config/store_test.go
lib/config/types.go
lib/config/types_test.go
lib/revision/control.go
lib/revision/github/control.go
templates/index.html
tools/deploy/deploy.go
tools/goshipcfg/main.go
tools/goshipcfg/v1.go

For ease of future extension
* added a tool to store/dump configs; also useful for migration of directory structure

Reorganize etcd directory strcuture

---

README.md
deploy_handler.go
deploy_log_handler.go
handlers/commits/handler.go
handlers/commits/payload.go
lib/acl/access_control.go
lib/config/load.go
lib/config/load_test.go
lib/config/store_test.go
lib/config/types.go
lib/github/client.go
lib/github/githubtest/stub.go
lib/revision/control.go
lib/revision/gcr/control.go
lib/revision/gcr/doc.go
lib/revision/gcr/name.go
lib/revision/gcr/registry.go
lib/revision/github/control.go
lib/revision/github/control_test.go
lib/revision/github/doc.go
main.go
plugins/pivotal/pivotal_test.go
plugins/travis/travis_test.go
templates/index.html

* Docker images must be stored in Google Container Registry
* TODO(yugui) Support generic v1 and v2 docker registries in another PR

Minimal support of Docker

---

Godeps/Godeps.json

Recently added dependencies were not on the list

Update Godep.json to add all dependencies

---

lib/config/types.go

the args order was wrong, it cause compare from the "letest" to "current"

pivotal_comment_fix

---

tools/deploy/deploy.go

The error was introduced in #173

Fix runtime parse error of deployment configuration

---

tools/deploy/deploy.go

Run berkshelf if Berksfile is available

---

lib/config/types.go

So we know what repository was deployed.

Add github repo name to pivotal deploy comment

---

static/js/pivotal.js

- Use `'` for strings
- Fix indenting

cleanup pivotal.js file

---

static/js/pivotal.js

Had a typo, and needed to filter array...

fix issues with pivotal.js :|

---

static/js/pivotal.js

`Gray`: repo has commits
`Green`: ready to deploy, changes were merged into master but not deployed
`Strikethrough`: deployed

Improve logic for showing dependency list: in progress, merged, deployed

---

lib/config/load.go
lib/config/load_test.go
lib/config/types.go
lib/revision/github/control.go

add HostType k8s to retrieve commit hash which saved in replication's label

add HostType k8s

---

lib/revision/github/control.go

use deployment instead of rc in k8s cluster

use deployment instead of replication controller

---

tools/deploy/deploy.go

should follow the deployEnv on cook

use specifed env to execute recipe

---

lib/config/types.go
lib/revision/github/control.go

make resource type and selector configurable so that we can retrieve any resource we want.

[#119342327] configurable k8s resource and selector

---

deploy_handler.go

fix printing a none exist parameter

---

lib/config/types.go

make `add_label` function configurable

[#121377935] configurable pivotal add label
